# Generated by Django 2.0.2 on 2021-04-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='orduser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nusername', models.CharField(max_length=250)),
                ('nfirstname', models.CharField(max_length=250)),
                ('nlastname', models.CharField(max_length=250)),
                ('nemail', models.CharField(max_length=250)),
                ('nphone', models.CharField(max_length=100)),
                ('naddress', models.CharField(max_length=250)),
                ('nuser_type', models.CharField(default='ordinaryuser', max_length=50)),
                ('npassword1', models.CharField(max_length=150)),
                ('npassword2', models.CharField(max_length=150)),
            ],
        ),
    ]
