# Generated by Django 2.0.2 on 2021-04-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='invuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('firstname', models.CharField(max_length=250)),
                ('lastname', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=250)),
                ('user_type', models.CharField(default='innovator', max_length=50)),
                ('password1', models.CharField(max_length=150)),
                ('password2', models.CharField(max_length=150)),
            ],
        ),
    ]
