# Generated by Django 2.0.2 on 2021-04-26 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('innovator', '0005_auto_20210426_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinary_username', models.CharField(max_length=200)),
                ('mix', models.CharField(max_length=200)),
                ('sub_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innovator.invuser')),
            ],
        ),
        migrations.RemoveField(
            model_name='subz',
            name='zlink',
        ),
        migrations.DeleteModel(
            name='subz',
        ),
    ]
