# Generated by Django 2.0.2 on 2021-04-27 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('innovator', '0006_auto_20210426_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inusername', models.CharField(max_length=200)),
                ('ordusername', models.CharField(max_length=200)),
                ('comment', models.CharField(max_length=500)),
                ('conid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innovator.product')),
            ],
        ),
    ]
