# Generated by Django 2.0.2 on 2021-04-27 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('innovator', '0007_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='commentz',
        ),
    ]
