# Generated by Django 2.0.2 on 2021-04-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovator', '0008_auto_20210427_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='sitetrans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transdate', models.DateTimeField()),
                ('amount', models.IntegerField()),
                ('key', models.IntegerField()),
            ],
        ),
    ]
