# Generated by Django 2.0.2 on 2021-04-28 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('innovator', '0009_sitetrans'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sitetrans',
        ),
    ]
