# Generated by Django 2.0.2 on 2021-04-28 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('innovator', '0011_sitetrans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitetrans',
            name='holder',
        ),
        migrations.DeleteModel(
            name='sitetrans',
        ),
    ]
