# Generated by Django 2.0.2 on 2021-04-28 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('innovator', '0013_sitetrans'),
    ]

    operations = [
        migrations.CreateModel(
            name='invtoken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('husername', models.CharField(max_length=200)),
                ('donateusername', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
                ('key', models.IntegerField()),
                ('inuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innovator.invuser')),
            ],
        ),
    ]
