# Generated by Django 2.0.2 on 2021-04-28 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('innovator', '0014_invtoken'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='invtoken',
            new_name='invtokenacc',
        ),
    ]
