# Generated by Django 2.0.2 on 2021-04-29 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('innovator', '0017_auto_20210429_0613'),
    ]

    operations = [
        migrations.CreateModel(
            name='invtokenacc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('husername', models.CharField(max_length=200)),
                ('donateusername', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
                ('mixd', models.CharField(max_length=350)),
                ('inuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innovator.invuser')),
                ('keyh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innovator.product')),
            ],
        ),
    ]
