# Generated by Django 2.0.2 on 2021-04-29 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usern', '0002_auto_20210425_1339'),
        ('innovator', '0019_auto_20210429_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='invtokenacc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('husername', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
                ('mixd', models.CharField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='sitetrans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donateusername', models.CharField(max_length=200)),
                ('transdate', models.DateTimeField()),
                ('amount', models.IntegerField()),
                ('key', models.IntegerField()),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usern.orduser')),
            ],
        ),
        migrations.AddField(
            model_name='invtokenacc',
            name='donateusername',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innovator.sitetrans'),
        ),
        migrations.AddField(
            model_name='invtokenacc',
            name='inuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innovator.invuser'),
        ),
        migrations.AddField(
            model_name='invtokenacc',
            name='keyh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innovator.product'),
        ),
    ]
