# Generated by Django 2.0.2 on 2021-04-30 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('innovator', '0021_todo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='product',
        ),
        migrations.DeleteModel(
            name='todo',
        ),
    ]
