# Generated by Django 2.0.2 on 2021-05-03 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('innovator', '0024_admin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin',
            new_name='admin_my',
        ),
    ]
